# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/n3/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/n3/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/oppo/n3/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:system/vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/oppo/n3/proprietary/etc/sensor_def_qcomdev.conf:system/etc/sensor_def_qcomdev.conf \
    vendor/oppo/n3/proprietary/vendor/lib/libAKM8963.so:system/vendor/lib/libAKM8963.so \
    vendor/oppo/n3/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/oppo/n3/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/oppo/n3/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/oppo/n3/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/oppo/n3/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so
PRODUCT_COPY_FILES += \
    vendor/oppo/n3/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/oppo/n3/proprietary/vendor/lib/hw/camera.vendor.msm8974.so:system/vendor/lib/hw/camera.vendor.msm8974.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/oppo/n3/proprietary/vendor/lib/libqomx_core.so:system/vendor/lib/libqomx_core.so \
    vendor/oppo/n3/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/oppo/n3/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    vendor/oppo/n3/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_common.so:system/vendor/lib/libchromatix_ov16825_common.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_common_1080p.so:system/vendor/lib/libchromatix_ov16825_common_1080p.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_common_480p.so:system/vendor/lib/libchromatix_ov16825_common_480p.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_default_video.so:system/vendor/lib/libchromatix_ov16825_default_video.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_default_video_front.so:system/vendor/lib/libchromatix_ov16825_default_video_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_hfr_120.so:system/vendor/lib/libchromatix_ov16825_hfr_120.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_hfr_120_front.so:system/vendor/lib/libchromatix_ov16825_hfr_120_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_hfr_60.so:system/vendor/lib/libchromatix_ov16825_hfr_60.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_hfr_60_front.so:system/vendor/lib/libchromatix_ov16825_hfr_60_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_liveshot.so:system/vendor/lib/libchromatix_ov16825_liveshot.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_liveshot_front.so:system/vendor/lib/libchromatix_ov16825_liveshot_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview.so:system/vendor/lib/libchromatix_ov16825_preview.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview_binning.so:system/vendor/lib/libchromatix_ov16825_preview_binning.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview_fb.so:system/vendor/lib/libchromatix_ov16825_preview_fb.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview_front.so:system/vendor/lib/libchromatix_ov16825_preview_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview_night.so:system/vendor/lib/libchromatix_ov16825_preview_night.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_preview_sports.so:system/vendor/lib/libchromatix_ov16825_preview_sports.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_snapshot.so:system/vendor/lib/libchromatix_ov16825_snapshot.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_snapshot_fb.so:system/vendor/lib/libchromatix_ov16825_snapshot_fb.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_snapshot_front.so:system/vendor/lib/libchromatix_ov16825_snapshot_front.so \
    vendor/oppo/n3/proprietary/vendor/lib/libchromatix_ov16825_snapshot_night.so:system/vendor/lib/libchromatix_ov16825_snapshot_night.so \
    vendor/oppo/n3/proprietary/vendor/lib/libllvd_smore.so:system/vendor/lib/libllvd_smore.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera2_q3a_special.so:system/vendor/lib/libmmcamera2_q3a_special.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_ov16825.so:system/vendor/lib/libmmcamera_ov16825.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_sunny_16825_eeprom.so:system/vendor/lib/libmmcamera_sunny_16825_eeprom.so \
    vendor/oppo/n3/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    vendor/oppo/n3/proprietary/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
    vendor/oppo/n3/proprietary/vendor/lib/libseemore.so:system/vendor/lib/libseemore.so \
    vendor/oppo/n3/proprietary/vendor/lib/libt2tmanager.so:system/vendor/lib/libt2tmanager.so \
    vendor/oppo/n3/proprietary/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so
