# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/r7/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890.config:system/etc/firmware/left.tfa9890.config \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890.speaker:system/etc/firmware/left.tfa9890.speaker \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_music_table.eq:system/etc/firmware/left.tfa9890_music_table.eq \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_music_table.preset:system/etc/firmware/left.tfa9890_music_table.preset \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_n1b12.patch:system/etc/firmware/left.tfa9890_n1b12.patch \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_n1c2.patch:system/etc/firmware/left.tfa9890_n1c2.patch \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_voice_table.eq:system/etc/firmware/left.tfa9890_voice_table.eq \
    vendor/oppo/r7/proprietary/etc/firmware/left.tfa9890_voice_table.preset:system/etc/firmware/left.tfa9890_voice_table.preset

PRODUCT_COPY_FILES += \
    vendor/oppo/r7/proprietary/etc/firmware/tp/15011/15011_FW_S3508_Tpk.img:system/etc/firmware/tp/15011/15011_FW_S3508_Tpk.img \
    vendor/oppo/r7/proprietary/etc/firmware/tp/15011/15011_Limit_Tpk.img:system/etc/firmware/tp/15011/15011_Limit_Tpk.img
