# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/msm8939-common/setup-makefiles.sh

ifneq ($(TARGET_IS_64_BIT),true)

PRODUCT_COPY_FILES += \
    vendor/oppo/msm8939-common/proprietary-32/bin/qseecomd:system/bin/qseecomd \
    vendor/oppo/msm8939-common/proprietary-32/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/oppo/msm8939-common/proprietary-32/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/oppo/msm8939-common/proprietary-32/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/oppo/msm8939-common/proprietary-32/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw

else

PRODUCT_COPY_FILES += \
    vendor/oppo/msm8939-common/proprietary-64/bin/qseecomd:system/bin/qseecomd \
    vendor/oppo/msm8939-common/proprietary-64/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/oppo/msm8939-common/proprietary-64/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/oppo/msm8939-common/proprietary-64/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/oppo/msm8939-common/proprietary-64/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw

endif
