# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/f1f/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/f1f/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/oppo/f1f/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/oppo/f1f/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/oppo/f1f/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
    vendor/oppo/f1f/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/oppo/f1f/proprietary/vendor/bin/msm_irqbalance:system/vendor/bin/msm_irqbalance \
    vendor/oppo/f1f/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/oppo/f1f/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/oppo/f1f/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/oppo/f1f/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/oppo/f1f/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/oppo/f1f/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/oppo/f1f/proprietary/vendor/etc/data/dsi_config.xml:system/vendor/etc/data/dsi_config.xml \
    vendor/oppo/f1f/proprietary/vendor/etc/data/netmgr_config.xml:system/vendor/etc/data/netmgr_config.xml \
    vendor/oppo/f1f/proprietary/vendor/etc/data/qmi_config.xml:system/vendor/etc/data/qmi_config.xml \
    vendor/oppo/f1f/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:system/vendor/firmware/cpp_firmware_v1_4_0.fw \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.mbn:system/vendor/firmware/venus.mbn \
    vendor/oppo/f1f/proprietary/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt \
    vendor/oppo/f1f/proprietary/vendor/etc/permissions/qcnvitems.xml:system/vendor/etc/permissions/qcnvitems.xml \
    vendor/oppo/f1f/proprietary/vendor/etc/permissions/qcrilhook.xml:system/vendor/etc/permissions/qcrilhook.xml \
    vendor/oppo/f1f/proprietary/vendor/lib/hw/camera.vendor.msm8916.so:system/vendor/lib/hw/camera.vendor.msm8916.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmm-qcamera.so:system/vendor/lib/libmm-qcamera.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqomx_core.so:system/vendor/lib/libqomx_core.so \
    vendor/oppo/f1f/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/oppo/f1f/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/oppo/f1f/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/oppo/f1f/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so \
    vendor/oppo/f1f/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/oppo/f1f/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/oppo/f1f/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/com.quicinc.cne.api@1.0.so:system/vendor/lib64/com.quicinc.cne.api@1.0.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/com.quicinc.cne.constants@1.0.so:system/vendor/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so

PRODUCT_PACKAGES += \
    libtime_genoff \
    qcrilmsgtunnel \
    TimeService \
    shutdownlistener \
    qcnvitems \
    qcrilhook
PRODUCT_COPY_FILES += \
    vendor/oppo/f1f/proprietary/vendor/bin/psensord:system/vendor/bin/psensord \
    vendor/oppo/f1f/proprietary/vendor/firmware/tp/15109/15109_GOODIX_UPDATE_TRULY.bin:system/vendor/firmware/tp/15109/15109_GOODIX_UPDATE_TRULY.bin \
    vendor/oppo/f1f/proprietary/vendor/lib/libactuator_dw9800w_s5k3l8.so:system/vendor/lib/libactuator_dw9800w_s5k3l8.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libactuator_dw9800w_s5k3l8_camcorder.so:system/vendor/lib/libactuator_dw9800w_s5k3l8_camcorder.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libactuator_dw9800w_s5k3l8_camera.so:system/vendor/lib/libactuator_dw9800w_s5k3l8_camera.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_common.so:system/vendor/lib/libchromatix_ov8856_common.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_default_video.so:system/vendor/lib/libchromatix_ov8856_default_video.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_hfr_120fps.so:system/vendor/lib/libchromatix_ov8856_hfr_120fps.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_hfr_60fps.so:system/vendor/lib/libchromatix_ov8856_hfr_60fps.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_hfr_90fps.so:system/vendor/lib/libchromatix_ov8856_hfr_90fps.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_liveshot.so:system/vendor/lib/libchromatix_ov8856_liveshot.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_preview.so:system/vendor/lib/libchromatix_ov8856_preview.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_preview_binding.so:system/vendor/lib/libchromatix_ov8856_preview_binding.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_preview_fb.so:system/vendor/lib/libchromatix_ov8856_preview_fb.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_small_video.so:system/vendor/lib/libchromatix_ov8856_small_video.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_snapshot.so:system/vendor/lib/libchromatix_ov8856_snapshot.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_ov8856_snapshot_fb.so:system/vendor/lib/libchromatix_ov8856_snapshot_fb.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_common.so:system/vendor/lib/libchromatix_s5k3l8_15109_common.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_common_panorama.so:system/vendor/lib/libchromatix_s5k3l8_15109_common_panorama.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_default_video.so:system/vendor/lib/libchromatix_s5k3l8_15109_default_video.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l8_15109_hfr_120fps.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_liveshot.so:system/vendor/lib/libchromatix_s5k3l8_15109_liveshot.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_preview.so:system/vendor/lib/libchromatix_s5k3l8_15109_preview.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_preview_cmcc.so:system/vendor/lib/libchromatix_s5k3l8_15109_preview_cmcc.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_preview_panorama.so:system/vendor/lib/libchromatix_s5k3l8_15109_preview_panorama.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_small_video.so:system/vendor/lib/libchromatix_s5k3l8_15109_small_video.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_snapshot.so:system/vendor/lib/libchromatix_s5k3l8_15109_snapshot.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_snapshot_cmcc.so:system/vendor/lib/libchromatix_s5k3l8_15109_snapshot_cmcc.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_snapshot_panorama.so:system/vendor/lib/libchromatix_s5k3l8_15109_snapshot_panorama.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libchromatix_s5k3l8_15109_zsl_off.so:system/vendor/lib/libchromatix_s5k3l8_15109_zsl_off.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_gt24c64a_eeprom.so:system/vendor/lib/libmmcamera_gt24c64a_eeprom.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_ov8856.so:system/vendor/lib/libmmcamera_ov8856.so \
    vendor/oppo/f1f/proprietary/vendor/lib/libmmcamera_s5k3l8_15109.so:system/vendor/lib/libmmcamera_s5k3l8_15109.so \
    vendor/oppo/f1f/proprietary/vendor/lib64/libcalmodule_memsic.so:system/vendor/lib64/libcalmodule_memsic.so
